### ISSUE TITLE
Latest WP compatibility? 

### ISSUE THREAD

**Issue by pete-leese** [EnhancedAthlete/EA-WP-AWS-SES-Bounce-Handler#8]
Hi,

Does this plugin work on the later wordpress releases and also does it inform the end-user when they login that their emails are getting bounced? 

Thanks.

Pete

**Comment by BrianHenryIE** [comment]
1. A much more updated version is at:
https://github.com/BrianHenryIE/bh-wp-aws-ses-bounce-handler

2. No. The main purpose of this was to avoid sending emails to bounced addresses because AWS SES will cancel your plan if you exceed a threhold. 
It does inform WooCommerce shop managers – when they open an order it displays a notice if the email address has bounced. To inform the user wouldn't be difficult but was never a goal.

**Comment by pete-leese** [comment]
Thanks for the reply. I have setup the updated plugin, but getting some errors:

```
WS SES Bounce Handler. Error: "Uncaught TypeError: fwrite(): Argument #1 ($stream) must be of type resource, int given in /bitnami/wordpress/wp-content/plugins/bh-wp-aws-ses-bounce-handler/vendor-prefixed/katzgrau/klogger/src/Logger.php:233
Stack trace:
#0 /bitnami/wordpress/wp-content/plugins/bh-wp-aws-ses-bounce-handler/vendor-prefixed/katzgrau/klogger/src/Logger.php(233): fwrite()
#1 /bitnami/wordpress/wp-content/plugins/bh-wp-aws-ses-bounce-handler/vendor-prefixed/katzgrau/klogger/src/Logger.php(221): BrianHenryIE\AWS_SES_Bounce_Handler\Katzgrau\KLogger\Logger->write()
#2 /bitnami/wordpress/wp-content/plugins/bh-wp-aws-ses-bounce-handler/vendor-prefixed/psr/log/Psr/Log/AbstractLogger.php(126): BrianHenryIE\AWS_SES_Bounce_Handler\Katzgrau\KLogger\Logger->log()
#3 /bitnami/wordpress/wp-content/plugins/bh-wp-aws-ses-bounce-handler/vendor-prefixed/brianhenryie/bh-wp-logger/src/api/class-bh-wp-psr-logger.php(183): Psr\Log\AbstractLogger->debug()
#4 /bitnami/wordpress/wp-content/plugins/bh-wp-aws-ses-bounce-handler/vendor-prefixed/psr/log/Psr/Log/LoggerTrait.php(127): BrianHenryIE\AWS_SES_Bounce_Handler\WP_Logger\API\BH_WP_PSR_Logger->log()
#5 /bitnami/wordpress/wp-content/plugins/bh-wp-aws-ses-bounce-handler/src/admin/class-bounce-handler-test.php(140): BrianHenryIE\AWS_SES_Bounce_Handler\WP_Logger\API\BH_WP_PSR_Logger->debug()
#6 /bitnami/wordpress/wp-content/plugins/bh-wp-aws-ses-bounce-handler/src/admin/class-ajax.php(102): BrianHenryIE\AWS_SES_Bounce_Handler\Admin\Bounce_Handler_Test->verify_test()
#7 /opt/bitnami/wordpress/wp-includes/class-wp-hook.php(324): BrianHenryIE\AWS_SES_Bounce_Handler\Admin\Ajax->fetch_test_results()
#8 /opt/bitnami/wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#9 /opt/bitnami/wordpress/wp-includes/plugin.php(517): WP_Hook->do_action()
#10 /opt/bitnami/wordpress/wp-admin/admin-ajax.php(192): do_action()
#11 {main}
thrown" at 2024-06-03T13:26:38Z UTC. [View Logs](https://www.xxxxxxx.com/wp-admin/admin.php?page=bh-wp-aws-ses-bounce-handler-logs&date=2024-06-03).
```

wp_mail() status WordPress is sending mail using /bitnami/wordpress/wp-content/plugins/wp-ses/wp-ses.php.

```
{ "type": 1, "message": "Uncaught TypeError: fwrite(): Argument #1 ($stream) must be of type resource, int given in \/bitnami\/wordpress\/wp-content\/plugins\/bh-wp-aws-ses-bounce-handler\/vendor-prefixed\/katzgrau\/klogger\/src\/Logger.php:233\nStack trace:\n#0 \/bitnami\/wordpress\/wp-content\/plugins\/bh-wp-aws-ses-bounce-handler\/vendor-prefixed\/katzgrau\/klogger\/src\/Logger.php(233): fwrite()\n#1 \/bitnami\/wordpress\/wp-content\/plugins\/bh-wp-aws-ses-bounce-handler\/vendor-prefixed\/katzgrau\/klogger\/src\/Logger.php(221): BrianHenryIE\\AWS_SES_Bounce_Handler\\Katzgrau\\KLogger\\Logger->write()\n#2 \/bitnami\/wordpress\/wp-content\/plugins\/bh-wp-aws-ses-bounce-handler\/vendor-prefixed\/psr\/log\/Psr\/Log\/AbstractLogger.php(126): BrianHenryIE\\AWS_SES_Bounce_Handler\\Katzgrau\\KLogger\\Logger->log()\n#3 \/bitnami\/wordpress\/wp-content\/plugins\/bh-wp-aws-ses-bounce-handler\/vendor-prefixed\/brianhenryie\/bh-wp-logger\/src\/api\/class-bh-wp-psr-logger.php(183): Psr\\Log\\AbstractLogger->debug()\n#4 \/bitnami\/wordpress\/wp-content\/plugins\/bh-wp-aws-ses-bounce-handler\/vendor-prefixed\/psr\/log\/Psr\/Log\/LoggerTrait.php(127): BrianHenryIE\\AWS_SES_Bounce_Handler\\WP_Logger\\API\\BH_WP_PSR_Logger->log()\n#5 \/bitnami\/wordpress\/wp-content\/plugins\/bh-wp-aws-ses-bounce-handler\/src\/admin\/class-bounce-handler-test.php(140): BrianHenryIE\\AWS_SES_Bounce_Handler\\WP_Logger\\API\\BH_WP_PSR_Logger->debug()\n#6 \/bitnami\/wordpress\/wp-content\/plugins\/bh-wp-aws-ses-bounce-handler\/src\/admin\/class-ajax.php(102): BrianHenryIE\\AWS_SES_Bounce_Handler\\Admin\\Bounce_Handler_Test->verify_test()\n#7 \/opt\/bitnami\/wordpress\/wp-includes\/class-wp-hook.php(324): BrianHenryIE\\AWS_SES_Bounce_Handler\\Admin\\Ajax->fetch_test_results()\n#8 \/opt\/bitnami\/wordpress\/wp-includes\/class-wp-hook.php(348): WP_Hook->apply_filters()\n#9 \/opt\/bitnami\/wordpress\/wp-includes\/plugin.php(517): WP_Hook->do_action()\n#10 \/opt\/bitnami\/wordpress\/wp-admin\/admin-ajax.php(192): do_action()\n#11 {main}\n thrown", "file": "\/bitnami\/wordpress\/wp-content\/plugins\/bh-wp-aws-ses-bounce-handler\/vendor-prefixed\/katzgrau\/klogger\/src\/Logger.php", "line": 233, "debug_backtrace": [ { "file": "\/bitnami\/wordpress\/wp-content\/plugins\/bh-wp-aws-ses-bounce-handler\/vendor-prefixed\/brianhenryie\/bh-wp-logger\/src\/api\/class-bh-wp-psr-logger.php", "lineNumber": 80, "arguments": [ "error", "Uncaught TypeError: fwrite(): Argument #1 ($stream) must be of type resource, int given in \/bitnami\/wordpress\/wp-content\/plugins\/bh-wp-aws-ses-bounce-handler\/vendor-prefixed\/katzgrau\/klogger\/src\/Logger.php:233\nStack trace:\n#0 \/bitnami\/wordpress\/wp-content\/plugins\/bh-wp-aws-ses-bounce-handler\/vendor-prefixed\/katzgrau\/klogger\/src\/Logger.php(233): fwrite()\n#1 \/bitnami\/wordpress\/wp-content\/plugins\/bh-wp-aws-ses-bounce-handler\/vendor-prefixed\/katzgrau\/klogger\/src\/Logger.php(221): BrianHenryIE\\AWS_SES_Bounce_Handler\\Katzgrau\\KLogger\\Logger->write()\n#2 \/bitnami\/wordpress\/wp-content\/plugins\/bh-wp-aws-ses-bounce-handler\/vendor-prefixed\/psr\/log\/Psr\/Log\/AbstractLogger.php(126): BrianHenryIE\\AWS_SES_Bounce_Handler\\Katzgrau\\KLogger\\Logger->log()\n#3 \/bitnami\/wordpress\/wp-content\/plugins\/bh-wp-aws-ses-bounce-handler\/vendor-prefixed\/brianhenryie\/bh-wp-logger\/src\/api\/class-bh-wp-psr-logger.php(183): Psr\\Log\\AbstractLogger->debug()\n#4 \/bitnami\/wordpress\/wp-content\/plugins\/bh-wp-aws-ses-bounce-handler\/vendor-prefixed\/psr\/log\/Psr\/Log\/LoggerTrait.php(127): BrianHenryIE\\AWS_SES_Bounce_Handler\\WP_Logger\\API\\BH_WP_PSR_Logger->log()\n#5 \/bitnami\/wordpress\/wp-content\/plugins\/bh-wp-aws-ses-bounce-handler\/src\/admin\/class-bounce-handler-test.php(140): BrianHenryIE\\AWS_SES_Bounce_Handler\\WP_Logger\\API\\BH_WP_PSR_Logger->debug()\n#6 \/bitnami\/wordpress\/wp-content\/plugins\/bh-wp-aws-ses-bounce-handler\/src\/admin\/class-ajax.php(102): BrianHenryIE\\AWS_SES_Bounce_Handler\\Admin\\Bounce_Handler_Test->verify_test()\n#7 \/opt\/bitnami\/wordpress\/wp-includes\/class-wp-hook.php(324): BrianHenryIE\\AWS_SES_Bounce_Handler\\Admin\\Ajax->fetch_test_results()\n#8 \/opt\/bitnami\/wordpress\/wp-includes\/class-wp-hook.php(348): WP_Hook->apply_filters()\n#9 \/opt\/bitnami\/wordpress\/wp-includes\/plugin.php(517): WP_Hook->do_action()\n#10 \/opt\/bitnami\/wordpress\/wp-admin\/admin-ajax.php(192): do_action()\n#11 {main}\n thrown", { "type": 1, "message": "Uncaught TypeError: fwrite(): Argument #1 ($stream) must be of type resource, int given in \/bitnami\/wordpress\/wp-content\/plugins\/bh-wp-aws-ses-bounce-handler\/vendor-prefixed\/katzgrau\/klogger\/src\/Logger.php:233\nStack trace:\n#0 \/bitnami\/wordpress\/wp-content\/plugins\/bh-wp-aws-ses-bounce-handler\/vendor-prefixed\/katzgrau\/klogger\/src\/Logger.php(233): fwrite()\n#1 \/bitnami\/wordpress\/wp-content\/plugins\/bh-wp-aws-ses-bounce-handler\/vendor-prefixed\/katzgrau\/klogger\/src\/Logger.php(221): BrianHenryIE\\AWS_SES_Bounce_Handler\\Katzgrau\\KLogger\\Logger->write()\n#2 \/bitnami\/wordpress\/wp-content\/plugins\/bh-wp-aws-ses-bounce-handler\/vendor-prefixed\/psr\/log\/Psr\/Log\/AbstractLogger.php(126): BrianHenryIE\\AWS_SES_Bounce_Handler\\Katzgrau\\KLogger\\Logger->log()\n#3 \/bitnami\/wordpress\/wp-content\/plugins\/bh-wp-aws-ses-bounce-handler\/vendor-prefixed\/brianhenryie\/bh-wp-logger\/src\/api\/class-bh-wp-psr-logger.php(183): Psr\\Log\\AbstractLogger->debug()\n#4 \/bitnami\/wordpress\/wp-content\/plugins\/bh-wp-aws-ses-bounce-handler\/vendor-prefixed\/psr\/log\/Psr\/Log\/LoggerTrait.php(127): BrianHenryIE\\AWS_SES_Bounce_Handler\\WP_Logger\\API\\BH_WP_PSR_Logger->log()\n#5 \/bitnami\/wordpress\/wp-content\/plugins\/bh-wp-aws-ses-bounce-handler\/src\/admin\/class-bounce-handler-test.php(140): BrianHenryIE\\AWS_SES_Bounce_Handler\\WP_Logger\\API\\BH_WP_PSR_Logger->debug()\n#6 \/bitnami\/wordpress\/wp-content\/plugins\/bh-wp-aws-ses-bounce-handler\/src\/admin\/class-ajax.php(102): BrianHenryIE\\AWS_SES_Bounce_Handler\\Admin\\Bounce_Handler_Test->verify_test()\n#7 \/opt\/bitnami\/wordpress\/wp-includes\/class-wp-hook.php(324): BrianHenryIE\\AWS_SES_Bounce_Handler\\Admin\\Ajax->fetch_test_results()\n#8 \/opt\/bitnami\/wordpress\/wp-includes\/class-wp-hook.php(348): WP_Hook->apply_filters()\n#9 \/opt\/bitnami\/wordpress\/wp-includes\/plugin.php(517): WP_Hook->do_action()\n#10 \/opt\/bitnami\/wordpress\/wp-admin\/admin-ajax.php(192): do_action()\n#11 {main}\n thrown", "file": "\/bitnami\/wordpress\/wp-content\/plugins\/bh-wp-aws-ses-bounce-handler\/vendor-prefixed\/katzgrau\/klogger\/src\/Logger.php", "line": 233 } ], "applicationFrame": true, "method": "log", "class": "BrianHenryIE\\AWS_SES_Bounce_Handler\\WP_Logger\\API\\BH_WP_PSR_Logger" }, { "file": "\/bitnami\/wordpress\/wp-content\/plugins\/bh-wp-aws-ses-bounce-handler\/vendor-prefixed\/brianhenryie\/bh-wp-logger\/src\/api\/class-bh-wp-psr-logger.php", "lineNumber": 52, "arguments": [ "Uncaught TypeError: fwrite(): Argument #1 ($stream) must be of type resource, int given in \/bitnami\/wordpress\/wp-content\/plugins\/bh-wp-aws-ses-bounce-handler\/vendor-prefixed\/katzgrau\/klogger\/src\/Logger.php:233\nStack trace:\n#0 \/bitnami\/wordpress\/wp-content\/plugins\/bh-wp-aws-ses-bounce-handler\/vendor-prefixed\/katzgrau\/klogger\/src\/Logger.php(233): fwrite()\n#1 \/bitnami\/wordpress\/wp-content\/plugins\/bh-wp-aws-ses-bounce-handler\/vendor-prefixed\/katzgrau\/klogger\/src\/Logger.php(221): BrianHenryIE\\AWS_SES_Bounce_Handler\\Katzgrau\\KLogger\\Logger->write()\n#2 \/bitnami\/wordpress\/wp-content\/plugins\/bh-wp-aws-ses-bounce-handler\/vendor-prefixed\/psr\/log\/Psr\/Log\/AbstractLogger.php(126): BrianHenryIE\\AWS_SES_Bounce_Handler\\Katzgrau\\KLogger\\Logger->log()\n#3 \/bitnami\/wordpress\/wp-content\/plugins\/bh-wp-aws-ses-bounce-handler\/vendor-prefixed\/brianhenryie\/bh-wp-logger\/src\/api\/class-bh-wp-psr-logger.php(183): Psr\\Log\\AbstractLogger->debug()\n#4 \/bitnami\/wordpress\/wp-content\/plugins\/bh-wp-aws-ses-bounce-handler\/vendor-prefixed\/psr\/log\/Psr\/Log\/LoggerTrait.php(127): BrianHenryIE\\AWS_SES_Bounce_Handler\\WP_Logger\\API\\BH_WP_PSR_Logger->log()\n#5 \/bitnami\/wordpress\/wp-content\/plugins\/bh-wp-aws-ses-bounce-handler\/src\/admin\/class-bounce-handler-test.php(140): BrianHenryIE\\AWS_SES_Bounce_Handler\\WP_Logger\\API\\BH_WP_PSR_Logger->debug()\n#6 \/bitnami\/wordpress\/wp-content\/plugins\/bh-wp-aws-ses-bounce-handler\/src\/admin\/class-ajax.php(102): BrianHenryIE\\AWS_SES_Bounce_Handler\\Admin\\Bounce_Handler_Test->verify_test()\n#7 \/opt\/bitnami\/wordpress\/wp-includes\/class-wp-hook.php(324): BrianHenryIE\\AWS_SES_Bounce_Handler\\Admin\\Ajax->fetch_test_results()\n#8 \/opt\/bitnami\/wordpress\/wp-includes\/class-wp-hook.php(348): WP_Hook->apply_filters()\n#9 \/opt\/bitnami\/wordpress\/wp-includes\/plugin.php(517): WP_Hook->do_action()\n#10 \/opt\/bitnami\/wordpress\/wp-admin\/admin-ajax.php(192): do_action()\n#11 {main}\n thrown", { "type": 1, "message": "Uncaught TypeError: fwrite(): Argument #1 ($stream) must be of type resource, int given in \/bitnami\/wordpress\/wp-content\/plugins\/bh-wp-aws-ses-bounce-handler\/vendor-prefixed\/katzgrau\/klogger\/src\/Logger.php:233\nStack trace:\n#0 \/bitnami\/wordpress\/wp-content\/plugins\/bh-wp-aws-ses-bounce-handler\/vendor-prefixed\/katzgrau\/klogger\/src\/Logger.php(233): fwrite()\n#1 \/bitnami\/wordpress\/wp-content\/plugins\/bh-wp-aws-ses-bounce-handler\/vendor-prefixed\/katzgrau\/klogger\/src\/Logger.php(221): BrianHenryIE\\AWS_SES_Bounce_Handler\\Katzgrau\\KLogger\\Logger->write()\n#2 \/bitnami\/wordpress\/wp-content\/plugins\/bh-wp-aws-ses-bounce-handler\/vendor-prefixed\/psr\/log\/Psr\/Log\/AbstractLogger.php(126): BrianHenryIE\\AWS_SES_Bounce_Handler\\Katzgrau\\KLogger\\Logger->log()\n#3 \/bitnami\/wordpress\/wp-content\/plugins\/bh-wp-aws-ses-bounce-handler\/vendor-prefixed\/brianhenryie\/bh-wp-logger\/src\/api\/class-bh-wp-psr-logger.php(183): Psr\\Log\\AbstractLogger->debug()\n#4 \/bitnami\/wordpress\/wp-content\/plugins\/bh-wp-aws-ses-bounce-handler\/vendor-prefixed\/psr\/log\/Psr\/Log\/LoggerTrait.php(127): BrianHenryIE\\AWS_SES_Bounce_Handler\\WP_Logger\\API\\BH_WP_PSR_Logger->log()\n#5 \/bitnami\/wordpress\/wp-content\/plugins\/bh-wp-aws-ses-bounce-handler\/src\/admin\/class-bounce-handler-test.php(140): BrianHenryIE\\AWS_SES_Bounce_Handler\\WP_Logger\\API\\BH_WP_PSR_Logger->debug()\n#6 \/bitnami\/wordpress\/wp-content\/plugins\/bh-wp-aws-ses-bounce-handler\/src\/admin\/class-ajax.php(102): BrianHenryIE\\AWS_SES_Bounce_Handler\\Admin\\Bounce_Handler_Test->verify_test()\n#7 \/opt\/bitnami\/wordpress\/wp-includes\/class-wp-hook.php(324): BrianHenryIE\\AWS_SES_Bounce_Handler\\Admin\\Ajax->fetch_test_results()\n#8 \/opt\/bitnami\/wordpress\/wp-includes\/class-wp-hook.php(348): WP_Hook->apply_filters()\n#9 \/opt\/bitnami\/wordpress\/wp-includes\/plugin.php(517): WP_Hook->do_action()\n#10 \/opt\/bitnami\/wordpress\/wp-admin\/admin-ajax.php(192): do_action()\n#11 {main}\n thrown", "file": "\/bitnami\/wordpress\/wp-content\/plugins\/bh-wp-aws-ses-bounce-handler\/vendor-prefixed\/katzgrau\/klogger\/src\/Logger.php", "line": 233 } ], "applicationFrame": true, "method": "error", "class": "BrianHenryIE\\AWS_SES_Bounce_Handler\\WP_Logger\\API\\BH_WP_PSR_Logger" }, { "file": "\/bitnami\/wordpress\/wp-content\/plugins\/bh-wp-aws-ses-bounce-handler\/vendor-prefixed\/brianhenryie\/bh-wp-logger\/src\/php\/class-php-shutdown-handler.php", "lineNumber": 87, "arguments": [], "applicationFrame": true, "method": "handle", "class": "BrianHenryIE\\AWS_SES_Bounce_Handler\\WP_Logger\\PHP\\PHP_Shutdown_Handler" }, { "file": "unknown", "lineNumber": 0, "arguments": [], "applicationFrame": false, "method": "[top]", "class": null } ], "filters": [ "wp_ajax_fetch_test_results" ] }
```

I tried to raise issue on the new repo, but appears "issues" is not enabled.
